
CREATE TABLE FOOD (
    FOOD_ID UUID PRIMARY KEY,
    FOOD_SLUG TEXT,
    FOOD_NAME TEXT,
    FOOD_IMAGE_URL TEXT,
    COST INT NOT NULL,
    FOOD_DIETARY_REQUIREMENTS JSON
);
CREATE TABLE VOTER(
    VOTER_ID UUID PRIMARY KEY, 
    TIME_VOTED DATETIME
)
CREATE TABLE VOTES(
    VOTES_ID UUID PRIMARY KEY,
    VOTER_ID UUID 
    FOREIGN KEY (VOTER_ID) REFERENCES VOTER(VOTER_ID)
)
